README.md, ngx_http_proxy_connect_module.c
Try to fix https://github.com/chobits/ngx_http_proxy_connect_module/issues/4.
=> proxy_connect_allow directive: support all ports & range of ports

README.md
Testing is updated to nginx-1.12.x.
=> README.md: updated tested nginx version

README.md, ngx_http_proxy_connect_module.c, t/http_proxy_connect.t
* added new variable $connect_addr: IP address and port of the remote host, e.g. "192.168.1.1:12345"
* added test case for $connect_host/$connect_port/$connect_addr
* added documentation of these variables
=> added new variable $connect_addr

ngx_http_proxy_connect_module.c
fix issue #32 
Signed-off-by: fengshuaitao <fengshuaitao@bytedance.com>
=> fix compile errors in ngx 1.9

t/http_proxy_connect.t
* create DNS server in test case instead of public dns server 8.8.8.8
* fixed failure of test case in mac os x
=> test case: remove dependence on public dns server

README.md
* has tested OpenResty 1.13.6.2 Compatibility
* updated Readme.md
* try to fixed https://github.com/chobits/ngx_http_proxy_connect_module/issues/26
=> added support to OpenResty

t/http_proxy_connect.t
1. added new test case to check that request will be forbidden without proxy_connect command enabled.
2. added debug log for test case
=> updated test case

ngx_http_proxy_connect_module.c, patch/proxy_connect.patch, patch/proxy_connect_1014.patch, patch/proxy_connect_rewrite.patch, patch/proxy_connect_rewrite_1014.patch
1. added new phase handler(POST_READ) to check CONNECT request
2. remove same logic from patches
=> simplify patch: move CONNECT request checking logic to module source

README.md, patch/proxy_connect_rewrite_1015.patch
* added new patch(support REWRITE phase) for nginx-1.15.2
* note that wont support patch that disables REWRITE phase
=> support nginx-1.15.2

README.md
typo fix: proxy_connect_write_timeout -> proxy_connect_send_timeout
=> updated README.md: fixed directive typo

ngx_http_proxy_connect_module.c, t/http_proxy_connect.t
fixed https://github.com/chobits/ngx_http_proxy_connect_module/issues/90
=> fixed bug that non CONNECT request triggers segfault without location

ngx_http_proxy_connect_module.c, t/http_proxy_connect.t
* proxy_connect_address: support dynamic domain resolving when nginx starts: Try to fix https://github.com/chobits/ngx_http_proxy_connect_module/issues/102
=> proxy_connect_address: support dynamic domain resolving

ngx_http_proxy_connect_module.c
*  proxy_connect resolver handler: fixed running posted requests, More details see nginx bugfix:n
* http://hg.nginx.org/nginx/rev/6169dbad37d8
* https://github.com/nginx/nginx/commit/efa61f42c10355263fd883e53f3e690fe01770a0
* refactor ngx_http_proxy_connect_create_peer()
=> refactor logic: add ngx_http_proxy_connect_create_peer() function

config
This updated config will make the module build a .so file. I am still in the middle of testing though, because I don't know if my config is wrong or if the module isn't working, because I am currently only getting `400` errors when trying to use CONNECT.
=> Updating make config to build a dynamic module

README.md, patch/proxy_connect_rewrite_1018.patch
Test case passed:
```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/Users/xiaochen/work/github/nginx-1.18.0/objs/nginx prove -v -I /Users/xiaochen/work/github/nginx-tests/lib ../ngx_http_proxy_connect_module/t
../ngx_http_proxy_connect_module/t/http_proxy_connect.t .......... 
+ test_enable_rewrite_phase: 1
+ DNS server: try to bind server port: 18085
+ DNS server: daemon pid: 74178
+ DNS server: working
ok 1 - 200 Connection Established
ok 2 - 200 Connection Established server name
ok 3 - 200 Connection Established server name
ok 4 - 200 Connection Established server name
ok 5 - 200 Connection Established not allowed port
ok 6 - Get method: proxy_pass
ok 7 - Get method: return 200
ok 8 - forbid CONNECT request without proxy_connect command enabled
ok 9 - proxy_remote_address supports …
```
=> updated REAMDE.md & patch file: support nginx 1.18.0

t/runtest.sh
```
$ sh runtest.sh
t/http_proxy_connect.t ..........
+ test_enable_rewrite_phase: 1
+ DNS server: try to bind server port: 18085
+ DNS server: daemon pid: 74980
+ DNS server: working
nginx: [warn] 512 worker_connections exceed open file resource limit: 256
ok 1 - 200 Connection Established
ok 2 - 200 Connection Established server name
ok 3 - 200 Connection Established server name
ok 4 - 200 Connection Established server name
ok 5 - 200 Connection Established not allowed port
ok 6 - Get method: proxy_pass
ok 7 - Get method: return 200
ok 8 - forbid CONNECT request without proxy_connect command enabled
....
```
=> test case: added runtest.sh

README.md
Lastest tested nginx version is 1.19.6.
=> updated README.md: update compatiility to nginx 1.19.x

README.md, ngx_http_proxy_connect_module.c, t/http_proxy_connect.t, t/http_proxy_connect_lua.t
* added new variable $proxy_connect_response
* added new test case t/http_proxy_connect_lua.t to test lua-nginx-module & $proxy_connect_response variable.
=> Feature: modify the CONNECT response via $proxy_connect_response

README.md, ngx_http_proxy_connect_module.c, t/http_proxy_connect.t
* added new directive `proxy_connect_response`
* added new test case for this directive
* readme updated
=> Feature: modify CONNECT response via proxy_connect_response directive

README.md
* test patch for nginx-1.22.0 (all test cases passed)
* update Readme
=> support nginx stable version to 1.22.0

README.md, ngx_http_proxy_connect_module.c, t/http_proxy_connect_resolve_variables.t
* added new variable $proxy_connect_first_byte_time
---
TODO: (DONT merge before following commit completed)
* ~~documentation for this feature~~(2022/7/27 done)
*  ~~test case for this feature~~(2022/7/29 done)
=> Feature: get the time to receive the first byte of data from proxy server

.github/workflows/ci.yml, t/genmake.sh, t/http_proxy_connect.t, t/http_proxy_connect_lua.t, t/http_proxy_connect_resolve_variables.t, t/http_proxy_connect_timeout.t
A test-case-pass version from my private proxy_connect module repo
Note that github action workflow ci/cd is hard to debug. So i clone proxy_connect module into a private repo for this test.
Anyone, who want to know how to build a complete nginx with lua-nginx-module and proxy_connect, can check this ci.yml
=> ci.yml: test nginx-1.22.1

.github/workflows/ci.yml, .github/workflows/test_openresty.yml
* auto testing with github action testing job
* auto testing result, see: https://github.com/chobits/ngx_http_proxy_connect_module/actions
[![test openresty](https://github.com/chobits/ngx_http_proxy_connect_module/actions/workflows/test_openresty.yml/badge.svg)](https://github.com/chobits/ngx_http_proxy_connect_module/actions/workflows/test_openresty.yml)
=> added auto test workflow for openresty

.github/workflows/ci.yml, .github/workflows/test_nginx_lastest_commit.yml, .github/workflows/test_openresty.yml, README.md
* used TEST_NGINX_GLOBALS_HTTP to add lua_pachage_path
* added workflow link into readme
=> README.md: added workflow link

.github/workflows/test_nginx_lastest_commit.yml
try to catch compilation error on clang for nginx latest commit
=> test_nginx_lastest_commit.yml: use clang as default compiler

README.md
fix ambiguity: https://github.com/chobits/ngx_http_proxy_connect_module/issues/273#issuecomment-1596578355
=> updated README.md: added a note for how to configure resolver directive
